'''
# Even Fibonacci numbers
# Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
fib_seq = [1,2]
new = 0
limit = 4000000

while new < limit:
    i = len(fib_seq)
    new = fib_seq[i-2] + fib_seq[i-1]

    if new >= limit:
        break
    else:
        fib_seq.append(new)

sum = 0
for num in fib_seq:
    if num % 2 == 0:
        sum += num



print(fib_seq)
print(sum)